### ISSUE TITLE
Pinout clarity

### ISSUE THREAD

**Issue by beachmiles** [shraiwi/ATTiny555#1]
Is soldering the 1 cap is all that is really needed?  
You say that the cap goes between PB0 and ground, what pin is PB0 on the tiny?
Your instructions show a video with 2 chips and tons of jumpers on 1 and another connected to something with an Arduino uno driving something. 
Then you have a motion gif with pinouts on post it notes showing a potential flip chip fix?
Did you flip the chip and bend all the pins 180°?
Your GitHub readme doesn't show anything about a cap.
Please clarify how exactly you made the tiny pin compatible with the 555.
https://hackaday.io/project/183013-attiny555

**Comment by knivd** [comment]
There are other varians which have GND exactly on pin 4. 
ATtiny11 or ATtiny25 for example

**Comment by shraiwi** [comment]
> You say that the cap goes between PB0 and ground, what pin is PB0 on the tiny?

Because this project is for the ATTiny85, the pinout of the chip is as follows:
![image](https://user-images.githubusercontent.com/40672030/146249169-ad762412-046f-4eb2-bf9e-ef410dd6179b.png)
The bottom two pins, **#5** (PB0) and **#4** (GND), are where you should solder the 68KOhm resistor.

> Your instructions show a video with 2 chips and tons of jumpers on 1 and another connected to something with an Arduino uno driving something.

The UNO was there to provide power and nothing else, and I'll be making a standalone circuit in the future. Also, the demo video was for the very first version of the prototype with an external voltage divider. The other components (jumpers, capacitors, etc.) were based on a real 555 circuit.

> Then you have a motion gif with pinouts on post it notes showing a potential flip chip fix?
Did you flip the chip and bend all the pins 180°?

That project log in question was referring to a *potential* way to make it pin-compatible, but as of right now it hasn't been done yet. I'll try to do it sometime in the coming week!

I hope this clarifies things!
\- Shraiwi

**Comment by beachmiles** [comment]
Pin #8 is VCC and not ground in your schematic screenshot.

**Comment by shraiwi** [comment]
Shoot, I'm sorry about that. I have no idea why I called it pin #8, it's actually pin #4. I've updated the diagram, thanks for pointing that out!
